export const FETCHING_PEOPLE_REQUEST = 'FETCHING_PEOPLE_REQUEST';
export const FETCHING_PEOPLE_REQUEST_suces = 'FETCHING_PEOPLE_REQUEST_suces';
export const FETCHING_PEOPLE_REQUEST_eror = 'FETCHING_PEOPLE_REQUEST_eror';

export const TT = 'TT';



//List Dasbord 
export const LIST_DASBOARD = 'LIST_DASBOARD';
export const LIST_DASBOARD_MENU = 'LIST_DASBOARD_MENU';

//List Dasbord Setting
export const LIST_DASBOARD_SETTING = 'LIST_DASBOARD_SETTING';
export const LIST_DASBOARD_MENU_SETTING = 'LIST_DASBOARD_MENU_SETTING';