export const FETCHING_PEOPLE_REQUEST = 'FETCHING_PEOPLE_REQUEST';
export const FETCHING_PEOPLE_REQUEST_suces = 'FETCHING_PEOPLE_REQUEST_suces';
export const FETCHING_PEOPLE_REQUEST_eror = 'FETCHING_PEOPLE_REQUEST_eror';

export const TT = 'TT';



//List Dasbord 
export const LIST_DASBOARD = 'LIST_DASBOARD';
export const LIST_DASBOARD_MENU = 'LIST_DASBOARD_MENU';

//List Dasbord Setting
export const LIST_DASBOARD_SETTING = 'LIST_DASBOARD_SETTING';
export const LIST_DASBOARD_MENU_SETTING = 'LIST_DASBOARD_MENU_SETTING';

//List Routers
export const LIST_ROUTER = 'LIST_ROUTER';


//List TK
export const LIST_DASBOARD_TK = 'LIST_DASBOARD_TK';
export const LIST_DASBOARD_MENU_TK = 'LIST_DASBOARD_MENU_TK';


//List SD
export const LIST_DASBOARD_SD = 'LIST_DASBOARD_SD';
export const LIST_DASBOARD_MENU_SD = 'LIST_DASBOARD_MENU_SD';

//List SMP
export const LIST_DASBOARD_SMP = 'LIST_DASBOARD_SMP';
export const LIST_DASBOARD_MENU_SMP = 'LIST_DASBOARD_MENU_SMP';

//List SMA
export const LIST_DASBOARD_SMA = 'LIST_DASBOARD_SMA';
export const LIST_DASBOARD_MENU_SMA = 'LIST_DASBOARD_MENU_SMA';

//List S1
export const LIST_DASBOARD_S1 = 'LIST_DASBOARD_S1';
export const LIST_DASBOARD_MENU_S1 = 'LIST_DASBOARD_MENU_S1';

//List CPNS
export const LIST_DASBOARD_CPNS = 'LIST_DASBOARD_CPNS';
export const LIST_DASBOARD_MENU_CPNS = 'LIST_DASBOARD_MENU_CPNS';

//List PROF
export const LIST_DASBOARD_PROF = 'LIST_DASBOARD_PROF';
export const LIST_DASBOARD_MENU_PROF = 'LIST_DASBOARD_MENU_PROF';